# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title
name: Jekyll Start
url: "http://localhost:4000" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
description: > # this means to ignore newlines until "keywords:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
keywords: jekyll, bootstrap, blogging, github pages, jekyll and bootstrap, seo, font awesome
favicon: /assets/img/favicon.png
image: /assets/img/jekyll-start.png
permalink: /:title
lang: es


# Default author
author:
   name: Ariel Sperduti
   email: ariel@sperduti.com.ar
   facebook: arielsperduti
   github: asperduti
   twitter: asperduti
   reddit: ''
   googleplus: ''
   linkedin: asperduti
   stackoverflow: ''
   instagram: arielsperduti
   youtube: ''



#Adsense code
adsense:
   client: ''
   slot: ''
   format: 'auto'


#Site Stats
google_analytics:

#Google Search console Verification
searchconsole_verification:

#Bing Webmaster tools Verification
bing_verification:

#Comments
disqus:
facebook_comments:

#Facebook
facebook_appid:
facebook_appversion: 'v2.11'
facebook_adminid:

socialmedia:
  facebook: jekyllstart
  twitter: jekyllstart
  googleplus: jekyllstart
  instagram: jekyllstart
  youtube: jekyllstart

# Don't need to change

# Plugins
plugins: [jekyll-paginate]

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 5

# Sass
sass:
  sass_dir: assets/_sass
  style: :compressed

include: ['_pages']

# Exclude these files from production site
exclude:
   - README.md
   - LICENSE
   - assets/_sass
   - assets/_js
   - .gitignore
